hakancelikdev/unimport

README.md
rare_cases/__future__.py
tests/future_action.py
tests/samples/future_acpected.py
tests/samples/star_action.py
tests/samples/star_expected.py
unimport/__main__.py
unimport/config.py
unimport/refactor.py
unimport/session.py

- write name change as remove
- permission add
- check add console improved 
-  _list_paths params name fix
- readme update

Console Argument

---

docs/AUTHORS.md
docs/CHANGELOG.md
tests/test_refactor.py
unimport/refactor.py

🐞 Fix: vertical style issue.

---

unimport/relate.py
unimport/scan.py

Refactor handling of string-type annotations

---

docs/CONTRIBUTING.md

Refix i88!!!

---

.github/codecov.yml
.isort.cfg
.vscode/settings.json
docs/CHANGELOG.md
requirements-dev.txt
tests/test_color.py
tests/test_metadata.py
tests/test_refactor.py
tests/test_session.py
tests/test_unused_import.py
unimport/config.py
unimport/refactor.py
unimport/session.py

Please don't merge before answering my question on issue #89

Improve test coverage i89

---

.github/codecov.yml

This will lead to %100 of test coverage.

Correct __main__.py file path

---

unimport/relate.py

Unnecessary control removed in relate.py file

---

unimport/main.py

Feel free to ask about any, but they are all self explanatory.

Slight code improvements in main.py

---

unimport/config.py

Unnecessary check remove

---

unimport/scan.py

Trying to speed things up a little bit.

Add lru_cache to get_duplicate_imports

---

unimport/utils.py

The cache on get_spec should speed things up a little bit at least.

Add cache to get_spec and shorted is_std function

---

.pre-commit-config.yaml

Remove seed-isort-config from pre-commit hooks.

---

.github/codecov.yml
.github/workflows/test.yml
docs/CHANGELOG.md
docs/_coverpage.md
requirements-dev.txt
setup.py
tests/test_scanner.py
tox.ini
unimport/constants.py
unimport/scan.py

V0.7.2 - Python3.9 Support

---

docs/CHANGELOG.md
docs/README.md
tests/configs/pyproject.toml
tests/configs/setup.cfg
tests/test_config.py
unimport/config.py
unimport/constants.py
unimport/main.py
unimport/utils.py

Add --ignore-init flag

---

.github/workflows/build-docs.yml
.github/workflows/test.yml
.pre-commit-config.yaml
docs/changelog.md
docs/index.md
setup.py
tests/analyzer/test_as_import.py
tests/analyzer/test_duplicate.py
tests/analyzer/test_scope.py
tests/analyzer/utils.py
tests/refactor/test_as_import.py
tests/refactor/test_duplicate_import.py
tests/refactor/test_scope.py
tests/refactor/utils.py
tests/test_utils.py
tox.ini
unimport/analyzer.py
unimport/config.py
unimport/constants.py
unimport/main.py
unimport/statement.py

Scope analyzer; #176, #175

---

docs/changelog.md
tests/refactor/test_style.py
unimport/refactor.py

Fix adding unnecessary rpar in vertical style #85, #190

---

MANIFEST.in
setup.py
unimport/utils.py

Don't depend on exact versions of dependencies

---

.dockerignore
.github/workflows/package-publish.yml
Dockerfile

Add package-publish workflow

---

.pre-commit-config.yaml
docs/changelog.md
docs/index.md
setup.py
tests/analyzer/test__analyzer.py
tests/test_color.py
tests/test_utils.py
unimport/__main__.py
unimport/analyzer.py
unimport/color.py
unimport/commands/__init__.py
unimport/commands/check.py
unimport/commands/diff.py
unimport/commands/options.py
unimport/commands/permission.py
unimport/commands/remove.py
unimport/config.py
unimport/constants.py
unimport/main.py

i199 Refactor options & commands & Option color output

---

.github/codecov.yml
.github/workflows/test.yml
docs/changelog.md
setup.py
tox.ini
unimport/constants.py

I26 - 3.10+ Support

---

.pre-commit-config.yaml
docs/changelog.md
docs/index.md
tests/cases/test_cases.py
tests/commands/test_check.py
tests/commands/test_options.py
tests/commands/test_parser.py
tests/test_utils.py
tox.ini
unimport/analyzer.py
unimport/commands/__init__.py
unimport/commands/options.py
unimport/commands/parser.py
unimport/main.py
unimport/utils.py

Fix: exit code behavior

---

.github/workflows/self-action.yml
.pre-commit-config.yaml
Dockerfile
action.yml
docs/changelog.md
docs/faq.md
docs/index.md
src/unimport/constants.py

#229 Add action.yml

---

.github/workflows/self-action.yml
docs/changelog.md
docs/faq.md
docs/index.md
setup.cfg
src/unimport/analyzer.py
src/unimport/color.py
src/unimport/commands/__init__.py
src/unimport/commands/check.py
src/unimport/commands/options.py
src/unimport/commands/parser.py
src/unimport/commands/permission.py
src/unimport/commands/remove.py
src/unimport/config.py
src/unimport/main.py
src/unimport/utils.py
tests/commands/test_check.py
tests/commands/test_options.py
tests/commands/test_parser.py
tests/config/configs/pyproject.toml
tests/config/configs/setup.cfg
tests/config/test_config.py

Remove requirements.txt related codes, features

---

.github/codecov.yml
docs/CHANGELOG.md
setup.cfg
src/unimport/__main__.py
src/unimport/main.py
src/unimport/utils.py
tests/test_linesep.py
tests/test_main.py
tests/test_utils.py

Refactor main.py and add tests

---

action.yml
docs/CHANGELOG.md
setup.cfg
src/unimport/__init__.py
src/unimport/analyzers/importable.py

Fix variable name

---

.pre-commit-config.yaml
action.yml
docs/CHANGELOG.md
docs/tutorial/use-with-github-action.md
src/unimport/__init__.py

release: 0.14.0

---

.pre-commit-config.yaml
action.yml
docs/CHANGELOG.md
docs/tutorial/use-with-github-action.md
pyproject.toml
src/unimport/__init__.py
src/unimport/config.py
tests/config/test_config.py
tests/conftest.py

fix: Running without options or a config file #281

---

.pre-commit-hooks.yaml
README.md
docs/CHANGELOG.md
docs/FAQ.md
docs/index.md
mkdocs.yml
pyproject.toml
setup.cfg
src/unimport/config.py
src/unimport/exceptions.py
src/unimport/meta.py
tests/config/configs/mistyped/pyproject.toml
tests/config/configs/mistyped/setup.cfg
tests/config/test_config.py

Raise more human-readable exceptions when the key is mistyped in the configuration. 

---

docs/CHANGELOG.md
docs/tutorial/configurations.md
src/unimport/config.py
tests/config/configs/like-commands/pyproject.toml
tests/config/configs/like-commands/setup.cfg
tests/config/test_config.py

Add support like command line commands in configuration files.

---

docs/FAQ.md

Typo in docs/FAQ.md

---

.pre-commit-config.yaml
action.yml
docs/CHANGELOG.md
docs/tutorial/use-with-github-action.md
src/unimport/__init__.py
src/unimport/config.py
tests/config/test_config.py

Fix: ignore-init setting is not working from command line call #263

---

.github/workflows/docs.yml
.github/workflows/pre-commit.yml
.github/workflows/pypi.yml
.github/workflows/test.yml
.github/workflows/unimport.yml
.pre-commit-config.yaml
action.yml
docs/CHANGELOG.md
docs/index.md
docs/tutorial/use-with-github-action.md
mkdocs.yml
setup.cfg
src/unimport/__init__.py
src/unimport/meta.py
tests/utils.py

Finally, version 1.0.0 is ready #271

---

.github/workflows/docs.yml
.github/workflows/pypi.yml
.github/workflows/test.yml
.pre-commit-config.yaml
docs/CHANGELOG.md
docs/CONTRIBUTING.md
docs/installation.md
docs/tutorial/command-line-options.md
pyproject.toml
setup.cfg
src/unimport/analyzers/import_statement.py
src/unimport/analyzers/utils.py
src/unimport/color.py
src/unimport/commands/check.py
src/unimport/commands/options.py
src/unimport/config.py
src/unimport/enums.py
src/unimport/main.py
src/unimport/refactor.py
src/unimport/statement.py
src/unimport/typing.py
src/unimport/utils.py
tests/config/test_config.py
tox.ini

Python 3.6 support dropped #306

---

.github/workflows/docs.yml
.github/workflows/pypi.yml
.github/workflows/test.yml
Dockerfile
docs/CHANGELOG.md
docs/CONTRIBUTING.md
pyproject.toml
setup.cfg
src/unimport/__init__.py
src/unimport/constants.py
tests/cases/analyzer/typing/type_parameter_syntax.py
tests/cases/refactor/typing/type_parameter_syntax.py
tests/cases/source/typing/type_parameter_syntax.py
tests/cases/test_cases.py
tox.ini

Python 3.12 support added
